In [2]:
[[123, 12, 123, 12, 33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [4]:
import numpy
n = numpy.arange(27)

In [10]:
m

NameError: name 'm' is not defined

In [12]:
m = numpy.asarray([[123,12,123,12,33]])

In [14]:
type(m)

numpy.ndarray

In [16]:
import cv2

In [23]:
im_rgb = cv2.imread("smallgray.png", 1)
im_g = cv2.imread("smallgray.png", 0)
print(im_g)
print(im_rgb)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [27]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [30]:
a = [1,2,3]
a[0:2]

[1, 2]

In [37]:
im_g[2,3]

97

In [40]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [42]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [45]:
ims = numpy.hstack((im_g,im_g))

In [47]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
imv = numpy.vstack((im_g, im_g))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [53]:
imv2 = numpy.vsplit(imv, 2)
imv2

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]